[about]
title = 'Test for rpgnotes'

[build]
source = 'test_pages'
macro-directory = 'test_macros'
css-files = ['/css/test-style.css']

[[collections]]
name = 'journals'
title = 'Journals'
reverse = true

[[collections]]
name = 'characters'
title = 'Characters'

[[collections]]
name = 'npcs'
title = 'NPCs'

[[collections]]
name = 'locations'
title = 'Locations'

[[collections]]
name = 'factions'
title = 'Factions'

[[collections]]
name = 'items'
title = 'Items'

[[collections]]
name = 'empty'
title = 'Empty'

[currencies.gold]
base-unit = 'gp'
precision = 2

[[currencies.gold.units]]
name = 'pp'
threshold = 1000
value = 10

[[currencies.gold.units]]
name = 'sp'
value = 0.1

[[currencies.gold.units]]
name = 'cp'
value = 0.01
